# Handle git submodules yourself
git:
  submodules: false

language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository

before_install:
  # Android SDK configuration
  - printenv
  - export ANDROID_SDK_ROOT=/usr/local/android-sdk
  - export PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools

  # Android NDK configuration
  - printenv
  - echo `pwd`
  - wget https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip
  - chmod a+x android-ndk-r14b-linux-x86_64.zip
  - unzip -qq android-ndk-r14b-linux-x86_64.zip -d $ANDROID_SDK_ROOT/ndk-bundle
  - ls -al $ANDROID_SDK_ROOT/ndk-bundle/android-ndk-r14b
  - export NDK_ROOT=$ANDROID_SDK_ROOT/ndk-bundle/android-ndk-r14b
  - echo $NDK_ROOT
  - export PATH=$PATH:$NDK_ROOT
  - echo $PATH

  - git clone --branch cocos2d-x-3.14.1 http://github.com/cocos2d/cocos2d-x.git
  - cd ./cocos2d-x
  - python download-deps.py -r yes
  - git submodule update --init
#  - mkdir ~/.cocos
#  - cp ../local_cfg.json ~/.cocos/local_cfg.json
#  - cat ~/.cocos/local_cfg.json
  - cd ./tools/cocos2d-console/
  - python download-bin.py -r yes
  - cd ../../
  - export COCOS_CONSOLE_ROOT=`pwd`/tools/cocos2d-console/bin
  - export PATH=$PATH:$COCOS_CONSOLE_ROOT
  - export COCOS_TEMPLATES_ROOT=`pwd`/templates
  - export PATH=$PATH:$COCOS_TEMPLATES_ROOT
  - export ANT_ROOT=/usr/share/ant/bin
  - export PATH=$PATH:$ANT_ROOT
  - cd ..
  - echo `pwd`
  - printenv
  # Do you agree to sent the data? [Y]es, [N]o
  - yes Y | cocos -v

script:
  - cocos compile -p android

notifications:
  email: false